let myDate= new Date()
console.log(myDate)
console.log(myDate.toLocaleDateString())
console.log(myDate.toLocaleString())
console.log(myDate.getMonth())
console.log(myDate.toString())
console.log(myDate.getTimezoneOffset())
console.log(myDate.getFullYear())
console.log(myDate.toLocaleTimeString())
console.log(typeof(myDate))